### ISSUE TITLE
HASwitchPlate Connected automation triggers multiple times

### ISSUE THREAD

**Issue by squirtbrnr** [aderusha/HASwitchPlate#7]
The HASwitchPlate_Connected automation triggers multiple (close to 15 times) when cycling power on the panel or when it reconnects to WiFi/MQTT

**Comment by squirtbrnr** [comment]
file: HASwitchPlatePages.yaml

**Comment by aderusha** [comment]
I can't seem to reproduce this behavior.  I've deployed a new instance of hass (currently `0.67.1`) and deployed the stock config from the repo here with the following command:
`svn export https://github.com/aderusha/HASwitchPlate/trunk/Home_Assistant ~/.homeassistant --force`

I started up Hass and configured the default state of the page selection buttons with the following commands:
```
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_text.haswitchplate_pagebutton1_label", "value": "scenes" }' http://localhost:8123/api/services/input_text/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_text.haswitchplate_pagebutton2_label", "value": "status" }' http://localhost:8123/api/services/input_text/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_text.haswitchplate_pagebutton3_label", "value": "media" }' http://localhost:8123/api/services/input_text/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_number.haswitchplate_pagebutton1_page", "value": 1}' http://localhost:8123/api/services/input_number/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_number.haswitchplate_pagebutton2_page", "value": 2}' http://localhost:8123/api/services/input_number/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_number.haswitchplate_pagebutton3_page", "value": 8}' http://localhost:8123/api/services/input_number/set_value
curl -X POST -H "x-ha-access: YOUR_PASSWORD" -H "Content-Type: application/json" -d '{ "entity_id": "input_number.haswitchplate_active_page", "value": 1}' http://localhost:8123/api/services/input_number/set_value
```
Once Hass has initialized I powered on the HASwitchPlate and observed all automations running once.  I power cycled the HASwitchPlate device several more times with Hass running and observed the same behavior each time.

Can you test this with a clean configuration by chance?  Is there any way another automation you've deployed might be interacting somehow?

**Comment by aderusha** [comment]
Disregard that, I just made it happen.  Not sure what is triggering that behavior, but I've now seen it happen on my stock configuration outlined above.  I'll dig into this, and thanks for the report!

**Comment by squirtbrnr** [comment]
I briefly dug through the arduino code and I'm thinking it has something to do with the MQTT connection sub-routine where it sets the connected state.

**Comment by aderusha** [comment]
I've narrowed the issue down to two compounding problems.  One is [an issue with Hass for which I have submitted a bug report](https://github.com/home-assistant/home-assistant/issues/14047).  With MQTT discovery enabled, hass is sending multiple replies in response to a single trigger.  This behavior is compounded by the page switching automations, which in certain cases can result in the page command being sent twice.  Because Hass is duplicating the automation response, the system can get stuck in a loop sending page commands back and forth, each of which triggers an additional cascade of MQTT messages until the Arduino code can't keep up and either resets or takes too long to respond to keep the loop going.  The result can be 10 or more responses on some of the page flipping automations.

**Comment by squirtbrnr** [comment]
that would explain the multiple page refreshes I experienced while using the built in MQTT broker.  The trigger on the connected automation is just the binary sensor being turned on.  so what you're saying is the MQTT discovery bug affects more than just the pages, but also the binary sensor state saying it's connected.  It's a race condition and the Arduino loses eventually.  I have seen the panel reboot itself but didn't know what contributed to it.  It was really prevalent when I was using the built in MQTT broker, but haven't seen it as much since using an external Mosquitto setup.

**Comment by aderusha** [comment]
This rabbit hole went deep.  I've rewritten large portions of the Arduino sketch, automations, and changed the namespace in order to avoid the issues outlined above.  I've just pushed version 0.2.0 which addresses this issue (and several others).

**Comment by squirtbrnr** [comment]
this is still occurring.  in fact I have the switch plate disconnected from power yet whenever I restart HA, the state goes back to "Connected" even though the switch plate is physically powered off, then the automation triggers now close to 25 times
